name: Update versions

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Fetch latest versions
        run: |
          VERSION=$(git ls-remote --tags https://git.busybox.net/busybox/ \
            | awk -F/ '!/[{}]/ {gsub(/_/, "."); print $3}' \
            | sort -V \
            | tail -1)

          set -u
          yq -i ".busybox= \"$VERSION\"" versions.yaml
          git diff versions.yaml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          branch: update-versions
          delete-branch: true
          title: Update BusyBox
          commit-message: Update BusyBox
